import {  Roboto } from 'next/font/google';
import './global.css';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700']
});

export const metadata = {
  title: 'Nextjs home page',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <div className="p-2 bg-slate-300">
            <h1 className='text-lg font-medium'>Logo</h1>
          </div>
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
};
